config/routes.rb
Olms::Application.routes.draw do

  resources :tutorials

  resources :dash_boards
  devise_for :users do
    get    "/users"         => "devise/registrations#edit", :as => :user_root
    post   "/users"         => "devise/sessions#new"
    get    "/users/sign_up" => "devise/sessions#new"
    delete "/users"         => "devise/sessions#new"
  end
  match '/signout',  to: 'sessions#destroy', via: :delete
  root to: 'dash_boards#index'

end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  attr_accessible :title, :description, :category, :video_url,:video_id, :active, :paid
  before_save :save_image_url
  
  def save_image_url
    if self.video_url.present? && self.video_id.present?
      self.image_url = "http://i1.ytimg.com/vi/#{video_id}/0.jpg"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:first_name,:last_name
  # attr_accessible :title, :body
  audited :allow_mass_assignment => true, :allow_mass_assignment => true
  has_associated_audits

  acts_as_paranoid
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  
  def store_location
    disable_pattern = /\/users/
    session[:previous_url] = request.fullpath unless request.fullpath =~ disable_pattern
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

  def after_sign_out_path_for(resource)
    after_sign_in_path_for(resource)
  end
end

app/controllers/dash_boards_controller.rb
class DashBoardsController < ApplicationController
  def index
    
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  
  def home
  end

  def employer
  end

  def jobseeker
  end

  def howitworks
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  # GET /tutorials
  # GET /tutorials.json
  def index
    @tutorials = Tutorial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tutorials }
    end
  end

  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
    @tutorial = Tutorial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tutorial }
    end
  end

  # GET /tutorials/new
  # GET /tutorials/new.json
  def new
    @tutorial = Tutorial.new(active: true)
 
    respond_to do |format|
      format.html {render layout: false}
      format.json { render json: @tutorial }
    end
  end

  # GET /tutorials/1/edit
  def edit
    @tutorial = Tutorial.find(params[:id])
  end

  # POST /tutorials
  # POST /tutorials.json
  def create
    @tutorial = Tutorial.new(params[:tutorial])

    respond_to do |format|
      if @tutorial.save
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully created.' }
        format.json { render json: @tutorial, status: :created, location: @tutorial }
      else
        format.html { render action: "new" }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tutorials/1
  # PUT /tutorials/1.json
  def update
    @tutorial = Tutorial.find(params[:id])

    respond_to do |format|
      if @tutorial.update_attributes(params[:tutorial])
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorials/1
  # DELETE /tutorials/1.json
  def destroy
    @tutorial = Tutorial.find(params[:id])
    @tutorial.destroy

    respond_to do |format|
      format.html { redirect_to tutorials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/dash_boards/index.html.erb
<% provide(:title, 'Online Learning Management System') %>
<div id="jobcarousel" class="carousel slide">
    <ol class="carousel-indicators">
     <% Tutorial.all.each_with_index do |tot,index| %>
       <li data-target="#jobcarousel" data-slide-to="<%= index%>" class="active"></li>
     <% end %>
    </ol>
    <!-- Carousel items -->
    <div class="carousel-inner">
      <% Tutorial.all.each_with_index do |tot,index| %>

      <div class="item <%= index == 0 ? 'active' : ''  %> video_img"  style="height:500px">
      <%= link_to image_tag(tot.image_url,style: 'margin-left:70px;width:800px;height:400px;cursor:pointer;',:class => 'image_vid'),"#" ,:data_url => tutorial_path(tot)  %>
        <div class="carousel-caption">
            <h4><%= tot.title %></h4>
            <p><%= tot.category %><p>
          </div>
          <div id="play" data_url="<%= tutorial_path(tot) %>">
          </div>
        </div>

      <% end %>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#jobcarousel" data-slide="prev" data-interval=5000 data-hover="pause">&lsaquo;</a>
    <a class="carousel-control right" href="#jobcarousel" data-slide="next" data-interval=5000 data-hover="pause">&rsaquo;</a>
  </div>

  <!%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
  <script>
   $("#play,.image_vid").on('click',function(){
    location.href = $(this).attr("data_url");
  })
  </script>

app/views/layouts/_footer.html.erb
<footer class="footer">
   <small>
    jobcube © 2013
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "OLMS", root_path, id: "logo" %>
      <% if !current_user %>
      <nav>
        <%= form_for(:user, :url => session_path('user'),:html => {:class => "navbar-search pull-right",:style => "margin-top:20px;"}) do |f| %>
          <input type="text" class="span2" name="user[email]" placeholder="User Name">
          <input type="password" class="span2" name="user[password]" placeholder="Password">
          <input type="submit" value="Login" class="btn btn-info" style="margin-bottom:14px;"/>
        <% end %>
      </nav>
      <% end %>
      <% if current_user %>
      <ul class="nav pull-right topnavfix">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Tutorials", tutorials_path %></li>
        <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            My Accounts <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Change Password", edit_user_registration_path %></li>
            <li><%= link_to "Payment Details", "#" %></li>
          </ul>
        </li>
        <li class="divider-vertical"></li>
        <li>
          <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
        </li>
      </ul>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title> <%= yield(:title) %></title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <br/>
    <div class="container">
      <% flash.each do |key, value| %>
         <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/staticpages/employer.html.erb
<% provide(:title, 'Employers') %>

<div class="center hero-unit ">
  <h1>Welcome. Your quest for talent search ends here </h1>
~                                     

app/views/staticpages/home.html.erb
<% provide(:title, 'Online Learning Management System') %>

<!--div class="center hero-unit ">
  <h1>Welcome to jobcube</h1>

-->

    <div id="jobcarousel" class="carousel slide">
    <ol class="carousel-indicators">
    <li data-target="#jobcarousel" data-slide-to="0" class="active"></li>
    <li data-target="#jobcarousel" data-slide-to="1"></li>
    <li data-target="#jobcarousel" data-slide-to="2"></li>
    </ol>
    <!-- Carousel items -->
    <div class="carousel-inner">
    <div class="active item">
      <%= link_to image_tag("slider-img1.jpg", alt: "jobcube") %>

      <embed
width="420" height="345"
src="http://www.youtube.com/v/XGSy3_Czz8k"
type="application/x-shockwave-flash">
</embed>

      
      <div class="carousel-caption">
        <h4>SCG</h4>
          <p>Skill Capture Genius.<p>
        </div>
    </div>
    <div class="item">
      <%= link_to image_tag("slider-img2.jpg", alt: "jobcube") %>
      <div class="carousel-caption">
        <h4>ISM</h4>
          <p>Intelligent Skill Match.<p>
        </div>
    </div>
    <div class="item">
       <%= link_to image_tag("slider-img3.jpg", alt: "jobcube") %>
       <div class="carousel-caption">
         <h4>AHA</h4>          
          <p>Advanced Heuristics Analysis.<p>
        </div>
    </div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#jobcarousel" data-slide="prev" data-interval=5000 data-hover="pause">&lsaquo;</a>
    <a class="carousel-control right" href="#jobcarousel" data-slide="next" data-interval=5000 data-hover="pause">&rsaquo;</a>
    </div>

  <!%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/staticpages/howitworks.html.erb
<% provide(:title, 'How It Works') %>

app/views/staticpages/jobseeker.html.erb
<% provide(:title, 'Job Seekers') %>

<div class="center hero-unit ">
  <h1>Welcome Job Seeker</h1>

app/views/tutorials/_form.html.erb
    <style type="text/css">
  #facebox .body {
    width: 500px;
  }
  </style>
  <script>
   $("#tutorial_video_url").on('change',function(){
   var regExp = /^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#\&\?]*).*/;
    var match = $("#tutorial_video_url").val().match(regExp);
    if (match&&match[7].length==11){
        $("#tutorial_video_id").val(match[7])
        return match[7];
    }else{
        alert("Url incorrecta");
    }
  })
  </script>
<div class="body facebox-div" style="width:450px;">
<%= form_for(@tutorial, :html => { :class => 'form-horizontal' }) do |f| %>
  <fieldset>
    <legend> Tutorial Details</legend>
    <%= f.hidden_field :video_id %>
    <div class="control-group">
      <%= f.label :title,:class => "control-label", :style => "text-align:left"%>
      <div class="controls" style="margin-left:100px;">
        <%= f.text_field :title,:class => "input-large","data-required" => true %>
        <% if @tutorial.errors && @tutorial.errors[:title].present? %>
          <span class="help-inline" id="error_explanation">
            <%= @tutorial.errors[:title][0] %>
          </span>
        <% end %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :category,:class => "control-label",:style => "text-align:left" %>
      <div class="controls" style="margin-left:100px;">
        <%= f.text_field :category,:class => "input-large","data-required" => true,:rows  => 4 %>
        <% if @tutorial.errors && @tutorial.errors[:category].present? %>
          <span class="help-inline" id="error_explanation">
            <%= @tutorial.errors[:category][0] %>
          </span>
        <% end %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :video_url,:class => "control-label",:style => "text-align:left" %>
      <div class="controls" style="margin-left:100px;">
        <%= f.text_field :video_url,:class => "input-large","data-required" => true,:rows  => 4 %>
        <% if @tutorial.errors && @tutorial.errors[:video_url].present? %>
          <span class="help-inline" id="error_explanation">
            <%= @tutorial.errors[:video_url][0] %>
          </span>
        <% end %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :paid,:class => "control-label",:style => "text-align:left" %>
      <div class="controls" style="margin-left:100px;">
        <%= f.check_box :paid,:class => "input-large","data-required" => true,:rows  => 4 %>
        <% if @tutorial.errors && @tutorial.errors[:paid].present? %>
          <span class="help-inline" id="error_explanation">
            <%= @tutorial.errors[:paid][0] %>
          </span>
        <% end %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :active,:class => "control-label",:style => "text-align:left" %>
      <div class="controls" style="margin-left:100px;">
        <%= f.check_box :active,:class => "input-large","data-required" => true,:rows  => 4 %>
        <% if @tutorial.errors && @tutorial.errors[:active].present? %>
          <span class="help-inline" id="error_explanation">
            <%= @tutorial.errors[:active][0] %>
          </span>
        <% end %>
      </div>
    </div>
    
    <div class="control-group">
       <div class="controls">
         <%= f.submit "Save", class: "btn btn-medium btn-primary" %>
         <%= link_to "cancel",tutorials_path ,class: "btn btn-medium btn-info" %>
       </div>
    </div>
  </fieldset>
<% end %>
</div>

app/views/tutorials/edit.html.erb
<h1>Editing tutorial</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutorial %> |
<%= link_to 'Back', tutorials_path %>

app/views/tutorials/index.html.erb
<% provide(:title, 'Online Learning Management System-Tutorials') %>
<fieldset>
  <legend>
    Tutorials
    <%= link_to "Add Tutorial",new_tutorial_path,:class => 'btn btn-info pull-right',:rel => "facebox" %>
  </legend>
  <table class="datatable table">
    <thead style="">
      <tr>
        <th data-toggle="true">
          Title
        </th>
        <th>
          Category
        </th>
        <th data-hide="phone,tablet">
          Active
        </th>
        <th data-hide="phone,tablet">
          Video URL
        </th>
        <th data-hide="phone,tablet">
          View Type
        </th>
      </tr>
    </thead>
    <tbody>
      <% @tutorials.each do |tot| %>
        <tr>
        <td><%= tot.title %> </td>
        <td><%= tot.category %> </td>
        <td><%= tot.active %></td>
        <td><%= tot.video_url %></td>
        <td><%= tot.paid %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</fieldset>

app/views/tutorials/new.html.erb
<%= render 'form' %>

app/views/tutorials/show.html.erb
<% provide(:title, 'Online Learning Management System') %>
<p id="notice"><%= notice %></p>
<iframe width="640" height="360" src="https://www.youtube.com/embed/<%= @tutorial.video_id%>?feature=player_embedded" frameborder="0" allowfullscreen></iframe>
<h1>Link will be provides to read text given by admin</h1>
<h1> Feed Back will appear with following features</h1>
<h4>Mail will be shoot to admin all feed backs/admin can setup filter with min/mix rating</h4>
<h4>viewers can give rating or (thumbsup/thumbs down) along with comments if required we can give control to admin to display comment given by viewer for monitoring</h4>
<%= link_to 'Back', root_path,:class => "btn" %>